-- Schema para H2 en tests
CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description CLOB,
    price DECIMAL(14,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    stock INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Datos semilla para tests
INSERT INTO product (sku, name, description, price, currency, stock, active)
VALUES ('SKU-001', 'Producto de ejemplo', 'Descripción inicial de producto', 199.90, 'ARS', 100, TRUE);
